### ISSUE TITLE
Runtime exited with error: signal: killed

### ISSUE THREAD

**Issue by kpmccaffrey** [cplankey/dynamo-to-s3-sar#1]
This is exactly what I needed today. But got the error when I tried to run it. 

Not a huge Dynamo DB. 7,000 items.

Fixed by increasing memory under Basic Settings. 

(I'm new to Node and Lambdas so not used to the configuration... might help someone else.)

**Comment by cplankey** [comment]
Great catch, there's a few ways I could solve this, curious what you think would be the best...

1. Over-provision the template with more memory than most people will need
2. Set the memory as a parameter when provisioning from the Serverless Application Repo (like the bucket and table name)
3. Update the readme to indicate this might happen for medium/large tables and provide snippets to show where to increase the memory

Which would you prefer? 

Thanks for the feedback! @kpmccaffrey

**Comment by kpmccaffrey** [comment]
I think updating the readme would be best. 

That's where I went back to when I started getting the error.
